function [rocketparamIDs, envparamIDs] = paramNames(SimObj)
%PARAMNAMES gives the names of the parameters that can be modified in the given simulator.
%   INPUT
%       SimObj          Simulator object
%   OUTPUTS
%       rocketparamIDs  Names of the rocket parameters
%       envparamIDs     Names of the environments parameters

if class(SimObj) == "multilayerwindSimulator3D" ... 
   || class(SimObj) == "multilayerwindSimulator3D_ode45" ... 
   || class(SimObj) == "multilayerwindSimulator3D_ode23" ...
   || class(SimObj) == "multilayerwindSimulator3D_ode113" ...
   || class(SimObj) == "multilayerwindSimulator3D_ode15s" ...
   || class(SimObj) == "multilayerwindSimulator3D_ode23s" ...
   || class(SimObj) == "multilayerwindSimulator3D_ode23t" ...
   || class(SimObj) == "multilayerwindSimulator3D_ode23tb"
        
    
    rocketparamIDs=["dmin" "dd" "z1" "z12" "z23" "fin_n" "fin_xt" "fin_s" "fin_cr" "fin_ct" "fin_xs" ...
                    "fin_t" "lug_n" "lug_S" "emptyMass" "emptyInertia" "emptyCenterOfMass" "ab_x" "ab_n" "ab_phi" ... 
                    "pl_mass" "para_main_SCD" "para_drogue_SCD" "para_main_event" "distanceInterMotors" "motor_diaP" ...
                    "motorLengthPropel" "massPropel" "motor_massP" "motor_diaF" "motorLengthFuel" "massFuel" ...
                    "motor_massF" "burnTime" "T1" "T2"];
                
    envparamIDs   =["Temperature_Ground" "Pressure_Ground" "Humidity_Ground"  ... 
                    "Start_Altitude" "dTdh" "Rail_Length" "Rail_Angle" "Rail_Azimuth"...
                    "Vi1" "Vi2" "Vi3" "Vi4" "Vi5" "Vi6" "ai1" "ai2" "ai3" "ai4" "ai5" "ai6"];
else
    error("Error: the sensitivity analysis is not implemented for this simulator")
end

end

