function windSpeed = windModel(time, turbulentIntensity, freeStreamVelocity, model, altitude)
% WINDMODEL computes wind based on specified Model. Wind can be constant or
% turbulent. Available models are:
% - None        : No wind change, wind is constant
% - Gaussian    : Stochastic wind intensity based on gaussian distribution
% - VonKarman   : Stochastic wind intensity based on VonKarman turbulence
%                 spectra
% INPUTS :
% - t           : simulation time [s]
% - I           : turbulent intensity = U_std/U_mean []
global windTimes
% windTimes: vector with times at which this function was previously called
global windSpeeds
% windSpeeds: vector with speeds generated by this function on previous calls

if(strcmp(model,'None'))
    % if the model is 'None', leave the wind speed
    % as that of free stream velocity
    windSpeed = freeStreamVelocity;
elseif(time == 0)
    if isempty(windTimes)
        % if uninitialized, initialize the global variables
        windTimes = 0;   
        windSpeeds = freeStreamVelocity;
    end
    windSpeed = freeStreamVelocity;
else
    % if the model is not 'None':
    %   if the specified time is earlier than the last stored time,
    %   linearly interpolate a windspeed based on previously generated speeds
    %   
    %   if the specified time is later than the last stored time,
    %   generate a new speed, and store the new time and speed into
    %   the corresponding global variables

    if isempty(windTimes)
        % if uninitialized, initialize the global variables
        windTimes = 0;   
        windSpeeds = freeStreamVelocity;
    end
    
    if(strcmp(model,'Gaussian'))
        if(time>windTimes(end))
            windTimes = [windTimes, time];
            turbDeviation = turbulentIntensity*freeStreamVelocity;
            windSpeed = normrnd(freeStreamVelocity, turbDeviation);
            windSpeeds = [windSpeeds, windSpeed]; 
        else
            windSpeed = interp1(windTimes, windSpeeds', time, 'linear')';
        end
        
    elseif(strcmp(model, 'VonKarman'))
        if(time>windTimes(end))
            windTimes = [windTimes, time];
            turbDeviation = turbulentIntensity*freeStreamVelocity;
            z0 = 0.001; % terrain roughness length [m] (desert)
            zi = 1000*Z0^(0.18);
            
            
            %TODO: complete model!!!!
            
            windSpeeds = [windSpeeds, windSpeed];
        else
            windSpeed = interp1(windTimes, windSpeeds', time, 'linear')';
        end
    elseif(strcmp(model, 'Logarithmic'))

            z0 = 0.0024; % [m]; % terrain roughness length [m] (desert)
            groundAltitude = 1.5; %[m] measure windspeed 
            windSpeed = freeStreamVelocity*(log(altitude/z0)/log(groundAltitude/z0));
            
            windSpeeds = [windSpeeds, windSpeed]; 
    else
        error('MATLAB:UnknownModelError',['Error: windmodel ' model 'is'...
         'unknown. Type help windModel to view available models.']);
    end
    
end

    function VKns = VK_long_norm_spectr(n, L2u, U_mean)
        % returns normalized longitudinal spetrum of tubulence at frequency
        % n, caracteristic length L2u and mean velocity U_mean.
        VKns = 4*n*L2u/U_mean/(1+70.8*(n*L2u/U_mean)^2)^5/6;
    end

    function VKns = VK_perp_norm_spectr(n, L2v, U_mean)
        % returns normalized perpendicular spetrum of tubulence at frequency
        % n, caracteristic length L2v and mean velocity U_mean.
        VKns = 4*(n*L2v/U_mean)*(1+755.2*(n*L2v/U_mean)^2)/(1+283.2*(n*L2v/U_mean)^2)^11/6;
    end

    function L2u = L2u_func(z, zi)
       if  z>zi
           L2u = 280;
       else
           L2u = 280*(z/zi)^(0.35);
       end
    end

    function L2v = L2v_func(z, zi)
       if  z>zi
           L2v = 140;
       else
           L2v = 140*(z/zi)^(0.48);
       end
    end

end